### ISSUE TITLE
set.seed() doesn't work

### ISSUE THREAD

**Issue by JayAhn0104** [yixuan/recosystem#15]
First of all thank you for sharing this wonderful library.

I'm currently working on a matrix completion project by using 'recosystem'.
And I'm very satisfied with this library mainly because of the fast training speed due to parallel computing.

But, there is a problem which the model does not give same results.
Although I enter "set.seed(2021)" right before the "$train", the prediction results are different. 

Since I am not familiar with C++, it is hard to manage by myself. 
Could you give me a relevant solution?

**Comment by yixuan** [comment]
Hi Jaehyeong, `recosystem` only guarantees that the results are reproducible if a single thread is used (`nthead = 1`). We cannot control the exact behaviour of multiple threads, since they will compete with each other to conduct the computation. It is mainly the design of the algorithm, not the code that implements it.

**Comment by JayAhn0104** [comment]
Thanks for your accurate response!
